import type { ModuleDef } from "@/lib/schema/types";

/** Academic modules. Science project is the fully-built flagship subtype. */
export const ACADEMIC_MODULES: ModuleDef[] = [
  {
    key: "research_question",
    name: "Research Question & Hypotheses",
    icon: "HelpCircle",
    presentation: "sheet",
    categoryAffinity: ["academic", "professional"],
    plural: "question",
    intro: "The question in one sentence, no sub-clauses. Everything downstream serves this.",
    gapRules: [
      { type: "field_empty", field: "question", message: "The research question isn't written down yet.", weight: 3 },
      { type: "field_empty", field: "measurable", message: "You haven't said what you can actually measure.", weight: 2 },
    ],
    entrySchema: [
      { key: "question", label: "The question, in one sentence", type: "text", isTitle: true, prompt: "No 'and', no sub-clauses. If it needs two sentences, it's two questions." },
      { key: "matters", label: "Why it matters", type: "longtext" },
      { key: "wrong", label: "What would prove you wrong", type: "longtext", prompt: "If you can't answer this, the question isn't empirical yet." },
      { key: "measurable", label: "What you can measure", type: "longtext", prompt: "With the access, time and equipment you actually have." },
      { key: "hypotheses", label: "Hypotheses", type: "longtext", repeatable: true },
    ],
  },
  {
    key: "hypothesis",
    name: "Hypothesis",
    icon: "FlaskConical",
    presentation: "sheet",
    categoryAffinity: ["academic"],
    plural: "hypothesis",
    intro: "The specific, testable prediction. If / then / because.",
    gapRules: [
      { type: "field_empty", field: "prediction", message: "The hypothesis has no stated prediction.", weight: 3 },
    ],
    entrySchema: [
      { key: "prediction", label: "If… then…", type: "text", isTitle: true, prompt: "If I change X, then Y will happen." },
      { key: "because", label: "Because…", type: "longtext", prompt: "The reasoning. What makes you expect this?" },
      { key: "null", label: "Null hypothesis", type: "text", prompt: "What you'd conclude if nothing happens." },
      { key: "measured_by", label: "Measured by", type: "text" },
    ],
  },
  {
    key: "variables",
    name: "Variables",
    icon: "Variable",
    presentation: "table",
    categoryAffinity: ["academic"],
    plural: "variables",
    intro: "Independent, dependent, controlled. Name every one you're touching or holding still.",
    gapRules: [
      { type: "min_entries", min: 2, message: "A test usually has at least an independent and a dependent variable — you've listed fewer." },
    ],
    entrySchema: [
      { key: "name", label: "Variable", type: "text", isTitle: true },
      { key: "kind", label: "Kind", type: "select", options: ["independent", "dependent", "controlled"] },
      { key: "how", label: "How it's measured / set", type: "text" },
      { key: "unit", label: "Unit", type: "text" },
    ],
  },
  {
    key: "methodology",
    name: "Methodology",
    icon: "ClipboardList",
    presentation: "sheet",
    categoryAffinity: ["academic"],
    plural: "method",
    intro: "Approach, sample, procedure, instruments, ethics — and why this method over the alternatives.",
    gapRules: [
      { type: "field_empty", field: "procedure", message: "The procedure isn't written down step by step yet.", weight: 2 },
      { type: "field_empty", field: "why_this", message: "You haven't justified this method over the alternatives." },
    ],
    entrySchema: [
      { key: "approach", label: "Approach", type: "text", isTitle: true },
      { key: "sample", label: "Sample / materials", type: "longtext", prompt: "Who or what, how many, how chosen." },
      { key: "procedure", label: "Procedure", type: "longtext", prompt: "Numbered steps. Someone else should be able to repeat it exactly." },
      { key: "instruments", label: "Instruments", type: "longtext" },
      { key: "ethics", label: "Ethics", type: "longtext" },
      { key: "why_this", label: "Why this method, not another", type: "longtext" },
    ],
  },
  {
    key: "data_observations",
    name: "Data & Observations",
    icon: "Table2",
    presentation: "table",
    categoryAffinity: ["academic", "professional"],
    plural: "records",
    intro: "The raw record. Structured, dated, unedited. Interpretation happens in Analysis, not here.",
    entrySchema: [
      { key: "label", label: "Trial / observation", type: "text", isTitle: true },
      { key: "when", label: "When", type: "date" },
      { key: "value", label: "Value", type: "number" },
      { key: "unit", label: "Unit", type: "text" },
      { key: "notes", label: "Notes", type: "longtext" },
    ],
  },
  {
    key: "analysis",
    name: "Analysis",
    icon: "LineChart",
    presentation: "list",
    categoryAffinity: ["academic", "professional"],
    plural: "findings",
    intro: "What the data says. One finding per entry, each pointing back at the records behind it.",
    entrySchema: [
      { key: "finding", label: "Finding", type: "text", isTitle: true },
      { key: "evidence", label: "Evidence", type: "reference", repeatable: true, refModules: ["data_observations", "sources"] },
      { key: "confidence", label: "How sure", type: "select", options: ["tentative", "moderate", "strong"] },
      { key: "caveats", label: "Caveats", type: "longtext" },
    ],
  },
  {
    key: "science_writeup",
    name: "Science Project Write-up",
    icon: "FileText",
    presentation: "slots",
    categoryAffinity: ["academic"],
    plural: "sections",
    intro: "The report, section by section. Fills in from the modules above as you go.",
    entrySchema: [
      { key: "section", label: "Section", type: "select", isTitle: true, slot: "section", options: [
        "Question", "Hypothesis", "Materials", "Procedure", "Observations", "Results", "Conclusion",
      ] },
      { key: "content", label: "Content", type: "longtext" },
    ],
  },
  {
    key: "literature_review",
    name: "Literature Review",
    icon: "Library",
    presentation: "table",
    categoryAffinity: ["academic"],
    plural: "sources",
    intro: "Source cards built for synthesis — argument, method, findings, limitations, relevance.",
    entrySchema: [
      { key: "title", label: "Source", type: "text", isTitle: true },
      { key: "argument", label: "Central argument", type: "longtext" },
      { key: "method", label: "Method", type: "text" },
      { key: "findings", label: "Findings", type: "longtext" },
      { key: "limitations", label: "Limitations", type: "text" },
      { key: "relevance", label: "Relevance to your work", type: "text" },
    ],
  },
  {
    key: "argument_map",
    name: "Argument Map",
    icon: "Network",
    presentation: "list",
    categoryAffinity: ["academic", "professional"],
    plural: "claims",
    intro: "Thesis, claims, evidence, counterarguments, rebuttals. The skeleton of the case you're making.",
    gapRules: [
      { type: "field_empty", field: "counter", message: "{title} has no counterargument. Every claim has one." },
    ],
    entrySchema: [
      { key: "claim", label: "Claim", type: "text", isTitle: true },
      { key: "supports", label: "Supports thesis by…", type: "text" },
      { key: "evidence", label: "Evidence", type: "longtext" },
      { key: "counter", label: "Counterargument", type: "longtext" },
      { key: "rebuttal", label: "Rebuttal", type: "longtext" },
    ],
  },
  {
    key: "essay_outline",
    name: "Essay Outline",
    icon: "AlignLeft",
    presentation: "list",
    categoryAffinity: ["academic", "professional"],
    plural: "paragraphs",
    defaultSort: "order",
    intro: "One row per paragraph. The 'what does this paragraph do' field is the point.",
    gapRules: [
      { type: "field_empty", field: "does", message: "{title} has no stated job.", weight: 2 },
    ],
    entrySchema: [
      { key: "label", label: "Paragraph", type: "text", isTitle: true },
      { key: "does", label: "What this paragraph does", type: "text", prompt: "Not what it's about — what work it does in the argument." },
      { key: "point", label: "Point", type: "longtext" },
      { key: "evidence", label: "Evidence used", type: "text" },
    ],
  },
  {
    key: "citations",
    name: "Citations",
    icon: "Quote",
    presentation: "table",
    categoryAffinity: ["academic"],
    plural: "citations",
    intro: "Every reference, in one style, exportable.",
    entrySchema: [
      { key: "key", label: "Cite key", type: "text", isTitle: true },
      { key: "authors", label: "Authors", type: "text" },
      { key: "year", label: "Year", type: "number" },
      { key: "title", label: "Title", type: "text" },
      { key: "publication", label: "Publication", type: "text" },
      { key: "doi", label: "DOI / URL", type: "link" },
    ],
  },
  {
    key: "rubric_requirements",
    name: "Rubric & Requirements",
    icon: "ListChecks",
    presentation: "list",
    categoryAffinity: ["academic", "professional"],
    plural: "requirements",
    intro: "Paste the brief. Turn every requirement into something you can check off.",
    entrySchema: [
      { key: "requirement", label: "Requirement", type: "text", isTitle: true },
      { key: "weight", label: "Weight / marks", type: "text" },
      { key: "met", label: "Met", type: "select", options: ["not yet", "partial", "done"] },
      { key: "evidence", label: "Where it's addressed", type: "text" },
    ],
  },
  {
    key: "study_plan",
    name: "Study Plan",
    icon: "CalendarRange",
    presentation: "table",
    categoryAffinity: ["academic"],
    plural: "topics",
    intro: "Syllabus broken down, confidence per topic, a revision schedule, weak areas surfaced.",
    entrySchema: [
      { key: "topic", label: "Topic", type: "text", isTitle: true },
      { key: "confidence", label: "Confidence", type: "rating", min: 1, max: 5 },
      { key: "last_reviewed", label: "Last reviewed", type: "date" },
      { key: "resources", label: "Resources", type: "longtext" },
      { key: "past_papers", label: "Past-paper questions done", type: "number" },
    ],
  },
  {
    key: "supervisor_log",
    name: "Supervisor Log",
    icon: "MessagesSquare",
    presentation: "timeline",
    categoryAffinity: ["academic"],
    plural: "meetings",
    defaultSort: "date",
    intro: "Every meeting: what was said, what was agreed, what to do next. Also the record of approvals.",
    entrySchema: [
      { key: "date", label: "Date", type: "date", isTitle: true, slot: "date" },
      { key: "discussed", label: "Discussed", type: "longtext" },
      { key: "agreed", label: "Agreed / approved", type: "longtext" },
      { key: "actions", label: "Actions before next time", type: "checklist" },
    ],
  },
  {
    key: "presentation",
    name: "Presentation",
    icon: "Presentation",
    presentation: "slots",
    categoryAffinity: ["academic", "professional"],
    plural: "sections",
    intro: "Audience and goal, the one-sentence takeaway, the narrative arc, the slide outline, delivery notes, anticipated questions.",
    gapRules: [
      { type: "field_empty", field: "takeaway", message: "You haven't written the one sentence you want them to leave with." },
    ],
    entrySchema: [
      { key: "part", label: "Part", type: "select", isTitle: true, slot: "part", options: [
        "Audience & goal", "One-sentence takeaway", "Narrative arc", "Slide outline", "Delivery notes", "Anticipated questions",
      ] },
      { key: "takeaway", label: "Content", type: "longtext" },
    ],
  },
];
