import type { ModuleDef } from "@/lib/schema/types";

/**
 * Creative modules. Novel is the fully-built flagship subtype (spec §20).
 * Field choice, order and prompt wording carry the craft (spec §5.2).
 */
export const CREATIVE_MODULES: ModuleDef[] = [
  {
    key: "premise",
    name: "Premise",
    icon: "Feather",
    presentation: "sheet",
    categoryAffinity: ["creative"],
    plural: "premise",
    intro:
      "The whole thing in a few sentences. If you can't write it yet, that's real information — try a brainstorm.",
    gapRules: [
      { type: "field_empty", field: "logline", message: "You haven't written a one-line version of this yet.", weight: 3 },
    ],
    entrySchema: [
      { key: "logline", label: "In one line", type: "text", isTitle: true, prompt: "One sentence. If a friend asked what you're writing, this is what you'd say." },
      { key: "hook", label: "The hook", type: "longtext", prompt: "What makes someone need to know what happens next?" },
      { key: "conflict", label: "Central conflict", type: "longtext", prompt: "Who wants what, and what stands in the way?" },
      { key: "stakes", label: "Stakes", type: "longtext", prompt: "What happens if they fail? Why should we care?" },
      { key: "setting", label: "Setting", type: "text", prompt: "Where and when — only the part that matters." },
      { key: "audience", label: "Who it's for", type: "text" },
    ],
  },
  {
    key: "characters",
    name: "Character Sheet",
    icon: "User",
    presentation: "sheet",
    categoryAffinity: ["creative"],
    plural: "characters",
    defaultSort: "created",
    intro:
      "One per major character. The order of these fields is deliberate — motivation first, appearance last.",
    suggestedWith: ["cast_overview", "relationship_map", "arc_tracker"],
    gapRules: [
      { type: "field_empty", field: "want", message: "{title} has no stated want.", weight: 3 },
      { type: "required_pairing", field: "lie", pairWith: "wound", message: "{title} believes a lie but you haven't written what made it feel true." },
    ],
    entrySchema: [
      { key: "name", label: "Name", type: "text", isTitle: true, required: true },
      { key: "role", label: "Role", type: "text", prompt: "Protagonist, antagonist, foil, mentor — or something you can't name yet." },
      { key: "one_line", label: "In one line", type: "text", prompt: "If a reader remembers one thing about them, what is it?" },
      { key: "want", label: "What they want", type: "longtext", prompt: "Concrete, external, statable in a sentence." },
      { key: "need", label: "What they need", type: "longtext", prompt: "The thing that would actually help — usually not the same." },
      { key: "lie", label: "The lie they believe", type: "longtext", prompt: "What they've decided is true that isn't." },
      { key: "wound", label: "Wound", type: "longtext", prompt: "What made the lie feel true." },
      { key: "arc", label: "Arc", type: "longtext", prompt: 'Start → end. "No change" is valid and sometimes better.' },
      { key: "contradiction", label: "Contradiction", type: "text", prompt: "One thing that doesn't fit the rest. People aren't consistent." },
      { key: "never", label: "What they'd never do", type: "text", prompt: "Often more revealing than what they would." },
      { key: "voice", label: "How they speak", type: "longtext", prompt: "Rhythm, vocabulary, what they avoid saying." },
      { key: "relationships", label: "Relationships", type: "reference", repeatable: true, refModules: ["characters"], prompt: "With what each one costs them." },
      { key: "appearance", label: "Appearance", type: "longtext", prompt: "Last, deliberately. Rarely the useful part." },
    ],
  },
  {
    key: "cast_overview",
    name: "Cast Overview",
    icon: "UsersRound",
    presentation: "table",
    categoryAffinity: ["creative"],
    plural: "roles",
    intro: "Everyone at a glance — role, function, and whether they earn their place.",
    entrySchema: [
      { key: "name", label: "Name", type: "reference", refModules: ["characters"], isTitle: true },
      { key: "function", label: "Function in the story", type: "text", prompt: "What would break if you cut them?" },
      { key: "first_appears", label: "First appears", type: "text" },
      { key: "last_appears", label: "Last appears", type: "text" },
    ],
  },
  {
    key: "relationship_map",
    name: "Relationship Map",
    icon: "Share2",
    presentation: "list",
    categoryAffinity: ["creative"],
    plural: "relationships",
    intro: "The charged connections. Each one is a tension, not just a label.",
    entrySchema: [
      { key: "pair", label: "Between", type: "text", isTitle: true, prompt: "e.g. Raven and her father" },
      { key: "nature", label: "What it is", type: "text" },
      { key: "tension", label: "The tension", type: "longtext", prompt: "What's unresolved between them?" },
      { key: "changes", label: "How it changes", type: "longtext" },
    ],
  },
  {
    key: "arc_tracker",
    name: "Arc Tracker",
    icon: "TrendingUp",
    presentation: "table",
    categoryAffinity: ["creative"],
    plural: "arcs",
    intro: "Where each character is, emotionally, at each major beat.",
    entrySchema: [
      { key: "character", label: "Character", type: "reference", refModules: ["characters"], isTitle: true },
      { key: "start", label: "At the start", type: "text" },
      { key: "midpoint", label: "At the midpoint", type: "text" },
      { key: "end", label: "At the end", type: "text" },
      { key: "turn", label: "The turn", type: "longtext", prompt: "The moment the change becomes irreversible." },
    ],
  },
  {
    key: "three_act",
    name: "Three-Act Structure",
    icon: "Columns3",
    presentation: "slots",
    categoryAffinity: ["creative"],
    plural: "beats",
    intro: "The load-bearing beats. Empty slots are the gap — a missing midpoint is a real problem.",
    gapRules: [
      { type: "empty_slot", message: "Act Two has no midpoint.", weight: 3 },
    ],
    entrySchema: [
      { key: "beat", label: "Beat", type: "select", isTitle: true, slot: "beat", options: [
        "Opening image", "Inciting incident", "End of Act One", "Midpoint", "Low point", "End of Act Two", "Climax", "Resolution",
      ] },
      { key: "what_happens", label: "What happens", type: "longtext" },
      { key: "why_it_turns", label: "Why it turns here", type: "longtext", prompt: "What changes that can't change back?" },
    ],
  },
  {
    key: "chapter_plan",
    name: "Chapter Plan",
    icon: "List",
    presentation: "list",
    categoryAffinity: ["creative"],
    plural: "chapters",
    defaultSort: "order",
    intro: "One row per chapter. Purpose first, then content.",
    gapRules: [
      { type: "field_empty", field: "purpose", message: "{title} has no stated purpose.", weight: 2 },
    ],
    entrySchema: [
      { key: "title", label: "Chapter", type: "text", isTitle: true },
      { key: "purpose", label: "What this chapter does", type: "text", prompt: "One job per chapter. If it has two, consider splitting it." },
      { key: "summary", label: "Summary", type: "longtext" },
      { key: "pov", label: "POV", type: "text" },
      { key: "target_words", label: "Target words", type: "number" },
    ],
  },
  {
    key: "scene_cards",
    name: "Scene Cards",
    icon: "GalleryHorizontal",
    presentation: "grid",
    categoryAffinity: ["creative"],
    plural: "scenes",
    intro: "One card per scene. What shifts, and who's present.",
    entrySchema: [
      { key: "title", label: "Scene", type: "text", isTitle: true },
      { key: "goal", label: "Whose scene / what they want", type: "text" },
      { key: "shift", label: "What changes", type: "longtext", prompt: "A scene where nothing changes is a scene to cut." },
      { key: "present", label: "Who's present", type: "reference", repeatable: true, refModules: ["characters"] },
      { key: "place", label: "Where", type: "reference", refModules: ["places"] },
      { key: "when", label: "When", type: "date" },
      { key: "chapter", label: "Chapter", type: "reference", refModules: ["chapter_plan"] },
    ],
  },
  {
    key: "places",
    name: "Places",
    icon: "MapPin",
    presentation: "gallery",
    categoryAffinity: ["creative"],
    plural: "places",
    intro: "Locations that carry weight. What the place does to the people in it.",
    entrySchema: [
      { key: "name", label: "Name", type: "text", isTitle: true, required: true },
      { key: "image", label: "Image", type: "image" },
      { key: "feel", label: "What it feels like", type: "longtext" },
      { key: "function", label: "What happens here", type: "text" },
      { key: "detail", label: "One telling detail", type: "text" },
    ],
  },
  {
    key: "history_timeline",
    name: "History & Timeline",
    icon: "CalendarClock",
    presentation: "timeline",
    categoryAffinity: ["creative"],
    plural: "events",
    defaultSort: "date",
    intro: "What happened before page one, and when. Dates here power the contradiction checks.",
    entrySchema: [
      { key: "event", label: "Event", type: "text", isTitle: true },
      { key: "date", label: "When", type: "date", slot: "date" },
      { key: "involves", label: "Involves", type: "reference", repeatable: true, refModules: ["characters"] },
      { key: "consequence", label: "Consequence", type: "longtext" },
    ],
  },
  {
    key: "themes_motifs",
    name: "Themes & Motifs",
    icon: "Palette",
    presentation: "list",
    categoryAffinity: ["creative"],
    plural: "themes",
    intro: "What the book is actually about, and the images that carry it. Kept honest against what the scenes do.",
    entrySchema: [
      { key: "theme", label: "Theme", type: "text", isTitle: true },
      { key: "question", label: "The question it poses", type: "text", prompt: "Themes are questions, not statements. What is the book asking?" },
      { key: "carried_by", label: "Carried by", type: "longtext", prompt: "Which characters, scenes, objects, or images make this land?" },
      { key: "motifs", label: "Motifs", type: "multiselect", options: [] },
    ],
  },
  {
    key: "pov_voice",
    name: "POV & Voice",
    icon: "Eye",
    presentation: "sheet",
    categoryAffinity: ["creative"],
    plural: "notes",
    intro: "The narrative stance and how it sounds. Decide it once, apply it everywhere.",
    entrySchema: [
      { key: "pov", label: "Point of view", type: "select", options: ["first", "close third", "distant third", "omniscient", "second", "shifting"], isTitle: true },
      { key: "tense", label: "Tense", type: "select", options: ["past", "present"] },
      { key: "narrator", label: "Who is telling this", type: "longtext", prompt: "Even in third person, someone is choosing the words. Who?" },
      { key: "distance", label: "Narrative distance", type: "longtext", prompt: "How close are we to the character's thoughts? Does it vary?" },
      { key: "sound", label: "How it sounds", type: "longtext", prompt: "Sentence rhythm, register, humour, what the narration notices." },
    ],
  },
  {
    key: "style_sheet",
    name: "Style Sheet",
    icon: "SpellCheck",
    presentation: "table",
    categoryAffinity: ["creative"],
    plural: "rules",
    intro: "The small consistency decisions — spelling, capitalisation, formatting — recorded as you make them.",
    entrySchema: [
      { key: "item", label: "Item", type: "text", isTitle: true },
      { key: "ruling", label: "How you're doing it", type: "text" },
      { key: "note", label: "Note", type: "text" },
    ],
  },
  // ── world / game / poetry (broader creative library) ──────────────────────
  {
    key: "magic_tech_system",
    name: "Magic / Technology System",
    icon: "Wand2",
    presentation: "sheet",
    categoryAffinity: ["creative"],
    plural: "systems",
    intro: "How the impossible works here. Rules matter more than powers.",
    gapRules: [
      { type: "field_empty", field: "limits", message: "This system has no stated limits.", weight: 3 },
    ],
    entrySchema: [
      { key: "name", label: "Name", type: "text", isTitle: true },
      { key: "how", label: "How it works", type: "longtext" },
      { key: "who", label: "Who can use it", type: "text" },
      { key: "cost", label: "What it costs", type: "longtext" },
      { key: "limits", label: "Limits", type: "longtext", required: true, prompt: "What can it absolutely not do? This is the important field." },
    ],
  },
  {
    key: "cultures_peoples",
    name: "Cultures & Peoples",
    icon: "Globe2",
    presentation: "gallery",
    categoryAffinity: ["creative"],
    plural: "cultures",
    intro: "Groups in the world — what they value, fear, and refuse.",
    entrySchema: [
      { key: "name", label: "Name", type: "text", isTitle: true },
      { key: "values", label: "What they value", type: "longtext" },
      { key: "taboo", label: "What is unthinkable to them", type: "text" },
      { key: "outsiders", label: "How they treat outsiders", type: "text" },
    ],
  },
  {
    key: "factions_power",
    name: "Factions & Power",
    icon: "Swords",
    presentation: "list",
    categoryAffinity: ["creative"],
    plural: "factions",
    intro: "Who holds power, who wants it, and what each would trade for it.",
    entrySchema: [
      { key: "name", label: "Faction", type: "text", isTitle: true },
      { key: "wants", label: "What they want", type: "text" },
      { key: "holds", label: "What power they hold", type: "text" },
      { key: "weakness", label: "Weakness", type: "text" },
    ],
  },
  {
    key: "language_naming",
    name: "Language & Naming",
    icon: "Languages",
    presentation: "table",
    categoryAffinity: ["creative"],
    plural: "entries",
    intro: "Sound patterns and naming rules, so invented words feel of a piece.",
    entrySchema: [
      { key: "term", label: "Word / name", type: "text", isTitle: true },
      { key: "meaning", label: "Meaning", type: "text" },
      { key: "rule", label: "Rule it follows", type: "text" },
    ],
  },
  {
    key: "rules_of_world",
    name: "Rules of the World",
    icon: "ScrollText",
    presentation: "list",
    categoryAffinity: ["creative"],
    plural: "rules",
    intro: "The physical, social and metaphysical laws you've committed to. Break one on purpose, never by accident.",
    entrySchema: [
      { key: "rule", label: "Rule", type: "text", isTitle: true },
      { key: "because", label: "Why it's true", type: "longtext" },
      { key: "exceptions", label: "Exceptions", type: "text" },
    ],
  },
  {
    key: "core_loop",
    name: "Core Loop",
    icon: "RefreshCw",
    presentation: "sheet",
    categoryAffinity: ["creative"],
    plural: "loop",
    intro: "The 30 seconds the player repeats for hours. If this isn't fun, nothing else matters.",
    entrySchema: [
      { key: "loop", label: "The loop, in steps", type: "longtext", isTitle: true, prompt: "Do X → get Y → spend Y on Z → repeat. Write the actual cycle." },
      { key: "fun", label: "Where the fun is", type: "longtext" },
      { key: "tension", label: "The decision each loop", type: "text", prompt: "What is the player choosing between every cycle?" },
    ],
  },
  {
    key: "mechanics",
    name: "Mechanics",
    icon: "Cog",
    presentation: "list",
    categoryAffinity: ["creative"],
    plural: "mechanics",
    intro: "Each rule of play, what it's for, and what it costs the player to learn.",
    entrySchema: [
      { key: "name", label: "Mechanic", type: "text", isTitle: true },
      { key: "does", label: "What it does", type: "longtext" },
      { key: "serves", label: "What experience it serves", type: "text" },
      { key: "teaches", label: "How the player learns it", type: "text" },
    ],
  },
  {
    key: "player_experience",
    name: "Player Experience Goals",
    icon: "Gamepad2",
    presentation: "list",
    categoryAffinity: ["creative"],
    plural: "goals",
    intro: "What you want the player to feel. Every design decision answers to these.",
    entrySchema: [
      { key: "feeling", label: "Feeling", type: "text", isTitle: true, prompt: "e.g. 'clever', 'overwhelmed then capable', 'lonely'" },
      { key: "when", label: "When", type: "text" },
      { key: "how", label: "How the design produces it", type: "longtext" },
    ],
  },
  {
    key: "poem_list",
    name: "Poem List",
    icon: "ListMusic",
    presentation: "list",
    categoryAffinity: ["creative"],
    plural: "poems",
    defaultSort: "order",
    intro: "Every poem, drafted or not, with its state and its job in the collection.",
    entrySchema: [
      { key: "title", label: "Title", type: "text", isTitle: true },
      { key: "state", label: "State", type: "select", options: ["idea", "drafting", "revising", "done"] },
      { key: "does", label: "What it does in the collection", type: "text" },
      { key: "notes", label: "Notes", type: "longtext" },
    ],
  },
  {
    key: "forms_constraints",
    name: "Forms & Constraints",
    icon: "Ruler",
    presentation: "table",
    categoryAffinity: ["creative"],
    plural: "forms",
    intro: "Formal rules you're working in or against.",
    entrySchema: [
      { key: "form", label: "Form / constraint", type: "text", isTitle: true },
      { key: "rule", label: "The rule", type: "text" },
      { key: "why", label: "Why use it here", type: "text" },
    ],
  },
  {
    key: "image_bank",
    name: "Image Bank",
    icon: "Aperture",
    presentation: "gallery",
    categoryAffinity: ["creative"],
    plural: "images",
    intro: "Concrete images and phrases to draw on. The raw sensory material.",
    entrySchema: [
      { key: "image", label: "Image / phrase", type: "text", isTitle: true },
      { key: "picture", label: "Picture", type: "image" },
      { key: "association", label: "What it carries", type: "text" },
    ],
  },
  {
    key: "collection_order",
    name: "Collection Order",
    icon: "ArrowDownUp",
    presentation: "list",
    categoryAffinity: ["creative"],
    plural: "positions",
    defaultSort: "order",
    intro: "The running order, and the logic of it — openings, turns, the last poem.",
    entrySchema: [
      { key: "poem", label: "Poem", type: "reference", refModules: ["poem_list"], isTitle: true },
      { key: "role", label: "Role in the sequence", type: "text" },
      { key: "transition", label: "How it follows the last", type: "text" },
    ],
  },
];
