import type { ModuleDef } from "@/lib/schema/types";

/** Personal modules. Trip is the fully-built flagship subtype. */
export const PERSONAL_MODULES: ModuleDef[] = [
  // ── Trip flagship set ──────────────────────────────────────────────────
  {
    key: "budget_sketch",
    name: "Budget Sketch",
    icon: "Calculator",
    presentation: "table",
    categoryAffinity: ["personal"],
    plural: "lines",
    intro: "A rough total before you commit to anything. Refine into a real Budget later.",
    entrySchema: [
      { key: "item", label: "Item", type: "text", isTitle: true },
      { key: "rough", label: "Rough cost", type: "money" },
      { key: "note", label: "Note", type: "text" },
    ],
  },
  {
    key: "trip_places",
    name: "Places",
    icon: "Map",
    presentation: "gallery",
    categoryAffinity: ["personal"],
    plural: "places",
    intro: "Everywhere you might go, why it's on the list, and how long it's worth.",
    entrySchema: [
      { key: "name", label: "Place", type: "text", isTitle: true, required: true },
      { key: "image", label: "Image", type: "image" },
      { key: "why", label: "Why go", type: "longtext" },
      { key: "time_needed", label: "Time worth spending", type: "text" },
      { key: "when_best", label: "Best time to visit", type: "text" },
      { key: "booked", label: "Needs booking ahead", type: "select", options: ["no", "yes"] },
    ],
  },
  {
    key: "trip_itinerary",
    name: "Itinerary",
    icon: "Route",
    presentation: "timeline",
    categoryAffinity: ["personal"],
    plural: "days",
    defaultSort: "date",
    intro: "Day by day. Loose is fine — the point is to see the shape and catch the impossible days.",
    entrySchema: [
      { key: "day", label: "Day", type: "text", isTitle: true },
      { key: "date", label: "Date", type: "date", slot: "date" },
      { key: "base", label: "Where you're based", type: "reference", refModules: ["trip_places"] },
      { key: "plan", label: "Plan", type: "longtext" },
      { key: "travel", label: "Travel that day", type: "text" },
      { key: "booked", label: "Booked", type: "checklist" },
    ],
  },
  {
    key: "bookings",
    name: "Bookings",
    icon: "Ticket",
    presentation: "table",
    categoryAffinity: ["personal"],
    plural: "bookings",
    intro: "Flights, trains, rooms, tickets. Reference numbers and dates in one place. Overlapping dates get flagged.",
    entrySchema: [
      { key: "what", label: "What", type: "text", isTitle: true },
      { key: "type", label: "Type", type: "select", options: ["flight", "train", "bus", "car", "accommodation", "activity", "other"] },
      { key: "start", label: "Start", type: "date", slot: "start" },
      { key: "end", label: "End", type: "date", slot: "end" },
      { key: "confirmation", label: "Confirmation #", type: "text" },
      { key: "cost", label: "Cost", type: "money" },
      { key: "status", label: "Status", type: "select", options: ["to book", "held", "booked", "paid"] },
    ],
  },
  {
    key: "packing_list",
    name: "Packing List",
    icon: "Luggage",
    presentation: "list",
    categoryAffinity: ["personal"],
    plural: "items",
    intro: "What to bring, grouped, checkable. Reused and refined every trip.",
    entrySchema: [
      { key: "category", label: "Category", type: "text", isTitle: true },
      { key: "items", label: "Items", type: "checklist" },
    ],
  },
  {
    key: "travel_documents",
    name: "Documents",
    icon: "IdCard",
    presentation: "list",
    categoryAffinity: ["personal"],
    plural: "documents",
    intro: "Passports, visas, insurance, vaccination records — with expiry dates and copies.",
    entrySchema: [
      { key: "name", label: "Document", type: "text", isTitle: true },
      { key: "holder", label: "Whose", type: "text" },
      { key: "number", label: "Number", type: "text" },
      { key: "expires", label: "Expires", type: "date" },
      { key: "copy", label: "Copy", type: "file" },
      { key: "status", label: "Status", type: "select", options: ["have it", "applied", "need to sort"] },
    ],
  },
  // ── Portfolio / website / life / home / learning ──────────────────────
  {
    key: "piece_list",
    name: "Piece List",
    icon: "LayoutGrid",
    presentation: "gallery",
    categoryAffinity: ["personal"],
    plural: "pieces",
    intro: "Everything you might include. What it shows about you, and whether it's ready.",
    entrySchema: [
      { key: "title", label: "Piece", type: "text", isTitle: true },
      { key: "image", label: "Image", type: "image" },
      { key: "shows", label: "What it demonstrates", type: "text" },
      { key: "year", label: "Year", type: "number" },
      { key: "ready", label: "Ready to show", type: "select", options: ["no", "needs work", "yes"] },
    ],
  },
  {
    key: "selection_criteria",
    name: "Selection Criteria",
    icon: "Filter",
    presentation: "list",
    categoryAffinity: ["personal"],
    plural: "criteria",
    intro: "How you decide what makes the cut. Write it down so the choices are consistent.",
    entrySchema: [
      { key: "criterion", label: "Criterion", type: "text", isTitle: true },
      { key: "why", label: "Why it matters for this portfolio", type: "text" },
    ],
  },
  {
    key: "portfolio_order",
    name: "Portfolio Order",
    icon: "ArrowDownUp",
    presentation: "list",
    categoryAffinity: ["personal"],
    plural: "positions",
    defaultSort: "order",
    intro: "The sequence. Open strong, close strong, vary the middle.",
    entrySchema: [
      { key: "piece", label: "Piece", type: "reference", refModules: ["piece_list"], isTitle: true },
      { key: "role", label: "Why here", type: "text" },
    ],
  },
  {
    key: "artist_statement",
    name: "Artist Statement",
    icon: "PenLine",
    presentation: "sheet",
    categoryAffinity: ["personal"],
    plural: "statement",
    intro: "What you make and why, in your own voice. Drafts welcome.",
    entrySchema: [
      { key: "draft", label: "Statement", type: "longtext", isTitle: true },
      { key: "themes", label: "Recurring concerns", type: "text" },
      { key: "audience", label: "Who it's written for", type: "text" },
    ],
  },
  {
    key: "bio",
    name: "Bio",
    icon: "UserCircle",
    presentation: "list",
    categoryAffinity: ["personal"],
    plural: "versions",
    intro: "Short, medium and long versions, kept current.",
    entrySchema: [
      { key: "length", label: "Length", type: "select", options: ["one-line", "50 words", "100 words", "full"], isTitle: true },
      { key: "text", label: "Text", type: "longtext" },
    ],
  },
  {
    key: "sitemap",
    name: "Sitemap",
    icon: "Sitemap",
    presentation: "list",
    categoryAffinity: ["personal"],
    plural: "pages",
    defaultSort: "order",
    intro: "Every page and how they nest. Keep it small.",
    entrySchema: [
      { key: "page", label: "Page", type: "text", isTitle: true },
      { key: "parent", label: "Under", type: "reference", refModules: ["sitemap"] },
      { key: "purpose", label: "What it's for", type: "text" },
    ],
  },
  {
    key: "page_content",
    name: "Page Content",
    icon: "FileType",
    presentation: "list",
    categoryAffinity: ["personal"],
    plural: "pages",
    intro: "The actual words for each page. Draft here, build elsewhere.",
    entrySchema: [
      { key: "page", label: "Page", type: "reference", refModules: ["sitemap"], isTitle: true },
      { key: "headline", label: "Headline", type: "text" },
      { key: "body", label: "Body", type: "longtext" },
      { key: "cta", label: "Call to action", type: "text" },
    ],
  },
  {
    key: "design_direction",
    name: "Design Direction",
    icon: "Brush",
    presentation: "gallery",
    categoryAffinity: ["personal"],
    plural: "references",
    intro: "Type, colour, feel — and the references that pin it down.",
    entrySchema: [
      { key: "label", label: "Reference", type: "text", isTitle: true },
      { key: "image", label: "Image", type: "image" },
      { key: "taking", label: "What you're taking from it", type: "text" },
    ],
  },
  {
    key: "tech_decisions",
    name: "Tech Decisions",
    icon: "Wrench",
    presentation: "list",
    categoryAffinity: ["personal"],
    plural: "decisions",
    intro: "Stack, hosting, tools — what you picked and what you turned down.",
    entrySchema: [
      { key: "decision", label: "Decision", type: "text", isTitle: true },
      { key: "chose", label: "Chose", type: "text" },
      { key: "over", label: "Over", type: "text" },
      { key: "why", label: "Why", type: "longtext" },
    ],
  },
  {
    key: "life_goal",
    name: "Goal",
    icon: "Mountain",
    presentation: "sheet",
    categoryAffinity: ["personal"],
    plural: "goal",
    intro: "What you're actually after, and why it matters enough to keep going when it's dull.",
    entrySchema: [
      { key: "goal", label: "The goal", type: "text", isTitle: true },
      { key: "why", label: "Why it matters", type: "longtext", prompt: "Be honest. The real reason, not the respectable one." },
      { key: "looks_like", label: "What 'done' looks like", type: "longtext" },
      { key: "by_when", label: "By when", type: "date" },
    ],
  },
  {
    key: "habits",
    name: "Habits",
    icon: "Repeat",
    presentation: "table",
    categoryAffinity: ["personal"],
    plural: "habits",
    intro: "The small recurring actions that add up to the goal.",
    entrySchema: [
      { key: "habit", label: "Habit", type: "text", isTitle: true },
      { key: "cadence", label: "How often", type: "text" },
      { key: "cue", label: "Cue", type: "text", prompt: "What triggers it? Attach it to something you already do." },
      { key: "last_done", label: "Last done", type: "date" },
    ],
  },
  {
    key: "obstacles_support",
    name: "Obstacles & Support",
    icon: "LifeBuoy",
    presentation: "list",
    categoryAffinity: ["personal"],
    plural: "items",
    intro: "What's likely to stop you, and who or what helps.",
    entrySchema: [
      { key: "obstacle", label: "Obstacle", type: "text", isTitle: true },
      { key: "when", label: "When it tends to hit", type: "text" },
      { key: "counter", label: "What helps", type: "longtext" },
      { key: "who", label: "Who can help", type: "text" },
    ],
  },
  {
    key: "rooms",
    name: "Rooms",
    icon: "DoorOpen",
    presentation: "gallery",
    categoryAffinity: ["personal"],
    plural: "rooms",
    intro: "Each space, what you want it to become, and the state it's in.",
    entrySchema: [
      { key: "room", label: "Room", type: "text", isTitle: true },
      { key: "image", label: "Current state", type: "image" },
      { key: "vision", label: "What you want", type: "longtext" },
      { key: "priority", label: "Priority", type: "select", options: ["someday", "this year", "now"] },
      { key: "budget", label: "Rough budget", type: "money" },
    ],
  },
  {
    key: "reno_decisions",
    name: "Decisions",
    icon: "CheckSquare",
    presentation: "table",
    categoryAffinity: ["personal"],
    plural: "decisions",
    intro: "Every choice — materials, finishes, fittings — with what you picked and the alternative.",
    entrySchema: [
      { key: "decision", label: "Decision", type: "text", isTitle: true },
      { key: "room", label: "Room", type: "reference", refModules: ["rooms"] },
      { key: "chosen", label: "Chosen", type: "text" },
      { key: "cost", label: "Cost", type: "money" },
      { key: "status", label: "Status", type: "select", options: ["deciding", "chosen", "ordered", "installed"] },
    ],
  },
  {
    key: "quotes_suppliers",
    name: "Quotes & Suppliers",
    icon: "ReceiptText",
    presentation: "table",
    categoryAffinity: ["personal"],
    plural: "quotes",
    intro: "Who quoted what, for what scope, and whether you'd use them.",
    entrySchema: [
      { key: "supplier", label: "Supplier", type: "text", isTitle: true },
      { key: "scope", label: "Scope", type: "text" },
      { key: "quote", label: "Quote", type: "money" },
      { key: "verdict", label: "Verdict", type: "select", options: ["waiting", "no", "maybe", "yes"] },
      { key: "contact", label: "Contact", type: "text" },
    ],
  },
  {
    key: "reno_sequence",
    name: "Sequence",
    icon: "ListOrdered",
    presentation: "list",
    categoryAffinity: ["personal"],
    plural: "steps",
    defaultSort: "order",
    intro: "The order the work has to happen in. Get this wrong and you're re-doing things.",
    entrySchema: [
      { key: "step", label: "Step", type: "text", isTitle: true },
      { key: "before", label: "Must happen before", type: "text" },
      { key: "who", label: "Who does it", type: "text" },
      { key: "done", label: "Done", type: "select", options: ["no", "yes"] },
    ],
  },
  {
    key: "learning_syllabus",
    name: "Syllabus",
    icon: "GraduationCap",
    presentation: "list",
    categoryAffinity: ["personal"],
    plural: "topics",
    defaultSort: "order",
    intro: "What you need to learn, in a sensible order, with a sense of how big each part is.",
    entrySchema: [
      { key: "topic", label: "Topic", type: "text", isTitle: true },
      { key: "why", label: "Why it matters", type: "text" },
      { key: "size", label: "Rough size", type: "select", options: ["an afternoon", "a week", "a month", "ongoing"] },
      { key: "done", label: "Confidence", type: "rating", min: 1, max: 5 },
    ],
  },
  {
    key: "practice_log",
    name: "Practice Log",
    icon: "Dumbbell",
    presentation: "timeline",
    categoryAffinity: ["personal"],
    plural: "sessions",
    defaultSort: "date",
    intro: "Each session — what you worked on, how it went, what to do next time.",
    entrySchema: [
      { key: "date", label: "Date", type: "date", isTitle: true, slot: "date" },
      { key: "focus", label: "Focus", type: "text" },
      { key: "minutes", label: "Minutes", type: "number" },
      { key: "went", label: "How it went", type: "longtext" },
      { key: "next", label: "Next time", type: "text" },
    ],
  },
  {
    key: "checkpoints",
    name: "Checkpoints",
    icon: "FlagTriangleRight",
    presentation: "list",
    categoryAffinity: ["personal"],
    plural: "checkpoints",
    intro: "How you'll know you're making progress — concrete things you'll be able to do.",
    entrySchema: [
      { key: "checkpoint", label: "I'll be able to…", type: "text", isTitle: true },
      { key: "by", label: "By roughly", type: "date" },
      { key: "reached", label: "Reached", type: "select", options: ["no", "yes"] },
    ],
  },
];
