import type { ModuleDef } from "@/lib/schema/types";

/** Professional modules. Campaign is the fully-built flagship subtype. */
export const PROFESSIONAL_MODULES: ModuleDef[] = [
  {
    key: "problem_opportunity",
    name: "Problem & Opportunity",
    icon: "Target",
    presentation: "sheet",
    categoryAffinity: ["professional"],
    plural: "statement",
    intro: "The problem in the customer's words, and why now.",
    entrySchema: [
      { key: "problem", label: "The problem", type: "longtext", isTitle: true, prompt: "In the words the person with the problem would use." },
      { key: "who", label: "Who has it", type: "text" },
      { key: "today", label: "How they solve it today", type: "longtext" },
      { key: "why_now", label: "Why now", type: "longtext" },
      { key: "size", label: "How big", type: "text" },
    ],
  },
  {
    key: "customer_audience",
    name: "Customer / Audience",
    icon: "UserSearch",
    presentation: "gallery",
    categoryAffinity: ["professional"],
    plural: "segments",
    intro: "Who you're for. What they believe now, and what they'd have to stop believing.",
    entrySchema: [
      { key: "name", label: "Segment", type: "text", isTitle: true },
      { key: "believes", label: "What they currently believe", type: "longtext" },
      { key: "stop_believing", label: "What they'd have to stop believing", type: "longtext" },
      { key: "where", label: "Where they already are", type: "text" },
      { key: "ignore", label: "What would make them ignore this", type: "text" },
      { key: "share", label: "What would make them share it", type: "text" },
    ],
  },
  {
    key: "value_proposition",
    name: "Value Proposition",
    icon: "Gift",
    presentation: "sheet",
    categoryAffinity: ["professional"],
    plural: "proposition",
    intro: "The one thing you do better than the alternative, stated plainly.",
    entrySchema: [
      { key: "statement", label: "For [who], who [need], we [what], unlike [alternative]", type: "longtext", isTitle: true },
      { key: "proof", label: "Why it's believable", type: "longtext" },
      { key: "not_for", label: "Who it's not for", type: "text" },
    ],
  },
  {
    key: "competitors",
    name: "Competitors",
    icon: "Crosshair",
    presentation: "table",
    categoryAffinity: ["professional"],
    plural: "competitors",
    intro: "Everyone solving this, including 'do nothing'. What they're good at, where the gap is.",
    entrySchema: [
      { key: "name", label: "Competitor", type: "text", isTitle: true },
      { key: "strength", label: "What they're good at", type: "text" },
      { key: "weakness", label: "Where they fall short", type: "text" },
      { key: "positioning", label: "How you're different", type: "text" },
    ],
  },
  {
    key: "business_model",
    name: "Business Model",
    icon: "Coins",
    presentation: "sheet",
    categoryAffinity: ["professional"],
    plural: "model",
    intro: "Revenue, costs, unit economics, and the assumptions holding it together.",
    entrySchema: [
      { key: "revenue", label: "How it makes money", type: "longtext", isTitle: true },
      { key: "pricing", label: "Pricing", type: "longtext" },
      { key: "costs", label: "Main costs", type: "longtext" },
      { key: "unit_economics", label: "Unit economics", type: "longtext", prompt: "What does one customer cost to get and serve, versus what they pay?" },
      { key: "assumptions", label: "Load-bearing assumptions", type: "longtext" },
    ],
  },
  {
    key: "go_to_market",
    name: "Go-to-Market",
    icon: "Rocket",
    presentation: "list",
    categoryAffinity: ["professional"],
    plural: "moves",
    intro: "How the first hundred, then the first thousand, hear about this.",
    entrySchema: [
      { key: "channel", label: "Channel", type: "text", isTitle: true },
      { key: "reaches", label: "Who it reaches", type: "text" },
      { key: "first_step", label: "First concrete step", type: "text" },
      { key: "cost", label: "Cost / effort", type: "text" },
    ],
  },
  {
    key: "risks_assumptions",
    name: "Risks & Assumptions",
    icon: "AlertTriangle",
    presentation: "table",
    categoryAffinity: ["professional"],
    plural: "risks",
    intro: "Each assumption, how confident you are, and the cheapest way to test it.",
    entrySchema: [
      { key: "assumption", label: "Assumption", type: "text", isTitle: true },
      { key: "confidence", label: "Confidence", type: "select", options: ["guess", "some evidence", "confident"] },
      { key: "impact", label: "If wrong…", type: "text" },
      { key: "test", label: "Cheapest way to test it", type: "text" },
    ],
  },
  {
    key: "product_requirements",
    name: "Product Requirements",
    icon: "ListTodo",
    presentation: "table",
    categoryAffinity: ["professional"],
    plural: "requirements",
    intro: "User stories with acceptance criteria and a priority. What 'done' means for each.",
    entrySchema: [
      { key: "story", label: "As a… I want… so that…", type: "longtext", isTitle: true },
      { key: "acceptance", label: "Acceptance criteria", type: "checklist" },
      { key: "priority", label: "Priority", type: "select", options: ["must", "should", "could", "won't"] },
      { key: "notes", label: "Notes", type: "longtext" },
    ],
  },
  {
    key: "roadmap",
    name: "Roadmap",
    icon: "Milestone",
    presentation: "timeline",
    categoryAffinity: ["professional"],
    plural: "items",
    defaultSort: "date",
    intro: "What ships when, and the one outcome each phase is chasing.",
    entrySchema: [
      { key: "item", label: "Item", type: "text", isTitle: true },
      { key: "phase", label: "Phase", type: "select", options: ["now", "next", "later"] },
      { key: "target", label: "Target date", type: "date", slot: "date" },
      { key: "outcome", label: "Outcome it's for", type: "text" },
    ],
  },
  {
    key: "stakeholders",
    name: "Stakeholders",
    icon: "Contact",
    presentation: "table",
    categoryAffinity: ["professional"],
    plural: "stakeholders",
    intro: "Who has a say, what they want, and how much influence they have.",
    entrySchema: [
      { key: "name", label: "Name", type: "text", isTitle: true },
      { key: "interest", label: "What they want from this", type: "text" },
      { key: "influence", label: "Influence", type: "select", options: ["low", "medium", "high"] },
      { key: "keep", label: "How to keep them onside", type: "text" },
    ],
  },
  {
    key: "meeting_feedback_log",
    name: "Meeting & Feedback Log",
    icon: "MessageSquareText",
    presentation: "timeline",
    categoryAffinity: ["professional"],
    plural: "entries",
    defaultSort: "date",
    intro: "What was said, by whom, and what you decided to do about it.",
    entrySchema: [
      { key: "date", label: "Date", type: "date", isTitle: true, slot: "date" },
      { key: "with", label: "With", type: "text" },
      { key: "feedback", label: "Feedback", type: "longtext" },
      { key: "response", label: "Your response / decision", type: "longtext" },
    ],
  },
  {
    key: "metrics",
    name: "Metrics",
    icon: "Gauge",
    presentation: "table",
    categoryAffinity: ["professional"],
    plural: "metrics",
    intro: "The few numbers that tell you if this is working. Baseline, target, current.",
    entrySchema: [
      { key: "name", label: "Metric", type: "text", isTitle: true },
      { key: "baseline", label: "Baseline", type: "number" },
      { key: "target", label: "Target", type: "number" },
      { key: "current", label: "Current", type: "number" },
      { key: "why", label: "Why this metric", type: "text" },
    ],
  },
  // ── Campaign flagship set ────────────────────────────────────────────────
  {
    key: "campaign_brief",
    name: "Campaign Brief",
    icon: "Megaphone",
    presentation: "sheet",
    categoryAffinity: ["professional"],
    plural: "brief",
    intro: "The whole campaign on one page. Objective, message, and what success looks like.",
    gapRules: [
      { type: "field_empty", field: "core_message", message: "The core message isn't written yet.", weight: 3 },
      { type: "field_empty", field: "success", message: "You haven't defined what a successful campaign looks like." },
    ],
    entrySchema: [
      { key: "objective", label: "Objective", type: "text", isTitle: true, prompt: "One sentence. What is this campaign for?" },
      { key: "core_message", label: "Core message", type: "longtext", prompt: "The one thing the audience should take away. Not a slogan — the idea." },
      { key: "single_minded", label: "If they remember one line", type: "text" },
      { key: "tone", label: "Tone", type: "text" },
      { key: "timing", label: "Timing / duration", type: "text" },
      { key: "success", label: "What success looks like", type: "longtext" },
      { key: "budget", label: "Budget", type: "money" },
    ],
  },
  {
    key: "campaign_audience",
    name: "Campaign Audience",
    icon: "Users2",
    presentation: "gallery",
    categoryAffinity: ["professional"],
    plural: "audiences",
    intro: "Who this is really for. Built the same way a character is — belief first.",
    gapRules: [
      { type: "field_empty", field: "stop_believing", message: "{title}: you haven't said what they'd have to stop believing." },
    ],
    entrySchema: [
      { key: "name", label: "Who they are", type: "text", isTitle: true },
      { key: "believes", label: "What they currently believe", type: "longtext" },
      { key: "stop_believing", label: "What they'd have to stop believing", type: "longtext" },
      { key: "where", label: "Where they already are", type: "text", prompt: "Channels, places, moments — where does this message reach them?" },
      { key: "ignore", label: "What would make them ignore this", type: "text" },
      { key: "share", label: "What would make them share it", type: "text" },
    ],
  },
  {
    key: "channel_plan",
    name: "Channel Plan",
    icon: "Radio",
    presentation: "table",
    categoryAffinity: ["professional"],
    plural: "channels",
    intro: "Each channel, the job it does, and the asset it needs. A channel with no asset is a gap.",
    gapRules: [
      { type: "field_empty", field: "asset", message: "{title} has no asset attached to it yet." },
    ],
    entrySchema: [
      { key: "channel", label: "Channel", type: "text", isTitle: true },
      { key: "job", label: "Job in the funnel", type: "select", options: ["awareness", "consideration", "conversion", "retention"] },
      { key: "audience", label: "Audience", type: "reference", refModules: ["campaign_audience"] },
      { key: "asset", label: "Asset needed", type: "reference", refModules: ["asset_list"] },
      { key: "budget", label: "Budget", type: "money" },
    ],
  },
  {
    key: "content_calendar",
    name: "Content Calendar",
    icon: "CalendarDays",
    presentation: "timeline",
    categoryAffinity: ["professional"],
    plural: "posts",
    defaultSort: "date",
    intro: "What goes out, where, and when. The campaign as a sequence of moments.",
    entrySchema: [
      { key: "title", label: "Piece", type: "text", isTitle: true },
      { key: "date", label: "Date", type: "date", slot: "date", required: true },
      { key: "channel", label: "Channel", type: "reference", refModules: ["channel_plan"] },
      { key: "status", label: "Status", type: "select", options: ["idea", "drafting", "review", "scheduled", "live"] },
      { key: "asset", label: "Asset", type: "reference", refModules: ["asset_list"] },
    ],
  },
  {
    key: "asset_list",
    name: "Asset List",
    icon: "FileStack",
    presentation: "table",
    categoryAffinity: ["professional"],
    plural: "assets",
    intro: "Every deliverable the campaign needs made, and who's making it.",
    entrySchema: [
      { key: "name", label: "Asset", type: "text", isTitle: true },
      { key: "format", label: "Format", type: "text" },
      { key: "owner", label: "Owner", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["not started", "in progress", "review", "final"] },
      { key: "due", label: "Due", type: "date" },
    ],
  },
  {
    key: "metrics_kpis",
    name: "Metrics & KPIs",
    icon: "ChartNoAxesCombined",
    presentation: "table",
    categoryAffinity: ["professional"],
    plural: "KPIs",
    intro: "The numbers that will tell you whether it landed. Set targets before launch, not after.",
    entrySchema: [
      { key: "name", label: "KPI", type: "text", isTitle: true },
      { key: "target", label: "Target", type: "number" },
      { key: "actual", label: "Actual", type: "number" },
      { key: "source", label: "Where it's measured", type: "text" },
    ],
  },
  // ── Event / launch set ──────────────────────────────────────────────────
  {
    key: "event_brief",
    name: "Event Brief",
    icon: "CalendarCheck",
    presentation: "sheet",
    categoryAffinity: ["professional", "personal"],
    plural: "brief",
    intro: "Who it's for, what they should leave saying, and the one thing that must not go wrong.",
    entrySchema: [
      { key: "purpose", label: "Purpose", type: "text", isTitle: true },
      { key: "for_who", label: "Who it's for", type: "text" },
      { key: "leave_saying", label: "What they should leave saying", type: "longtext" },
      { key: "must_not", label: "The one thing that must not go wrong", type: "text" },
      { key: "date", label: "Date", type: "date" },
      { key: "venue", label: "Venue", type: "text" },
    ],
  },
  {
    key: "run_of_show",
    name: "Run of Show",
    icon: "ClockAlert",
    presentation: "timeline",
    categoryAffinity: ["professional", "personal"],
    plural: "moments",
    defaultSort: "order",
    intro: "Minute by minute. What happens, who owns it, what has to be ready first, and what breaks if it runs late.",
    entrySchema: [
      { key: "time", label: "Time", type: "text", isTitle: true },
      { key: "what", label: "What happens", type: "text" },
      { key: "who", label: "Who's responsible", type: "text" },
      { key: "prereq", label: "Ready beforehand", type: "text" },
      { key: "if_late", label: "What breaks if this runs late", type: "text" },
    ],
  },
  {
    key: "vendors",
    name: "Vendors",
    icon: "Truck",
    presentation: "table",
    categoryAffinity: ["professional", "personal"],
    plural: "vendors",
    intro: "Who's supplying what, for how much, confirmed or not.",
    entrySchema: [
      { key: "name", label: "Vendor", type: "text", isTitle: true },
      { key: "supplies", label: "Supplies", type: "text" },
      { key: "cost", label: "Cost", type: "money" },
      { key: "status", label: "Status", type: "select", options: ["shortlisted", "quoted", "booked", "paid"] },
      { key: "contact", label: "Contact", type: "text" },
    ],
  },
  {
    key: "contingencies",
    name: "Contingencies",
    icon: "Umbrella",
    presentation: "list",
    categoryAffinity: ["professional", "personal"],
    plural: "contingencies",
    intro: "What could go wrong and what you'll do about it. An event with no contingency is a gap.",
    entrySchema: [
      { key: "risk", label: "If this happens…", type: "text", isTitle: true },
      { key: "plan", label: "…we do this", type: "longtext" },
      { key: "trigger", label: "Decide by", type: "text" },
      { key: "owner", label: "Owner", type: "text" },
    ],
  },
  {
    key: "guest_list",
    name: "Guest List",
    icon: "UserPlus",
    presentation: "table",
    categoryAffinity: ["professional", "personal"],
    plural: "guests",
    intro: "Who's invited, who's replied, who needs what.",
    entrySchema: [
      { key: "name", label: "Name", type: "text", isTitle: true },
      { key: "rsvp", label: "RSVP", type: "select", options: ["invited", "yes", "no", "maybe"] },
      { key: "plus", label: "Plus", type: "number" },
      { key: "needs", label: "Dietary / access needs", type: "text" },
      { key: "table", label: "Table / group", type: "text" },
    ],
  },
];
