import type { ModuleDef } from "@/lib/schema/types";

/**
 * Universal module set — available to every project (spec §6.1).
 * Rant Space and Open Questions have bespoke surfaces; their definitions here
 * exist so they appear in the library and the data model stays uniform.
 */
export const UNIVERSAL_MODULES: ModuleDef[] = [
  {
    key: "rant_space",
    name: "Rant Space",
    icon: "Mic",
    presentation: "timeline",
    universal: true,
    plural: "rants",
    intro:
      "Everything you think about this project, in the order you thought it. No structure, no decisions. Mine it later.",
    entrySchema: [
      { key: "body", label: "What's in your head", type: "longtext", isTitle: true },
    ],
  },
  {
    key: "open_questions",
    name: "Open Questions",
    icon: "CircleHelp",
    presentation: "list",
    universal: true,
    plural: "questions",
    intro:
      "The spine of the project. Every unknown you're tracking. Not knowing is progress, not a warning.",
    entrySchema: [
      { key: "text", label: "The question", type: "text", isTitle: true, required: true },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: ["blocking", "important", "minor"],
        prompt: "Blocking means you genuinely can't proceed. Reserve it, or everything turns red.",
      },
      { key: "answer", label: "Answer", type: "longtext", prompt: "Required when you resolve it. The record of what you decided is worth more than the checkbox." },
    ],
  },
  {
    key: "ideas",
    name: "Ideas",
    icon: "Lightbulb",
    presentation: "grid",
    universal: true,
    plural: "ideas",
    intro:
      "Unsorted material. Anything that might matter. Fed automatically from brainstorm answers you didn't route anywhere.",
    entrySchema: [
      { key: "title", label: "Idea", type: "text", isTitle: true },
      { key: "detail", label: "More", type: "longtext" },
      { key: "tags", label: "Tags", type: "multiselect", options: [] },
    ],
  },
  {
    key: "notes",
    name: "Notes",
    icon: "StickyNote",
    presentation: "list",
    universal: true,
    plural: "notes",
    intro: "Freeform. Things you want written down that don't belong to a structured module yet.",
    entrySchema: [
      { key: "title", label: "Title", type: "text", isTitle: true },
      { key: "body", label: "Note", type: "longtext" },
    ],
  },
  {
    key: "tasks",
    name: "Tasks",
    icon: "SquareCheckBig",
    presentation: "board",
    universal: true,
    plural: "tasks",
    intro: "What has to get done, elsewhere. To do / doing / done, with an owner and a due date.",
    defaultSort: "order",
    entrySchema: [
      { key: "title", label: "Task", type: "text", isTitle: true, required: true },
      { key: "status", label: "Status", type: "select", options: ["todo", "doing", "done"], slot: "status" },
      { key: "notes", label: "Notes", type: "longtext" },
      { key: "due", label: "Due", type: "date" },
      { key: "owner", label: "Owner", type: "text" },
      { key: "priority", label: "Priority", type: "select", options: ["low", "normal", "high"] },
      { key: "relates_to", label: "Relates to", type: "reference", refModules: ["*"], prompt: "A scene, a chapter, an experiment, a vendor — whatever this task is for." },
    ],
  },
  {
    key: "milestones",
    name: "Milestones",
    icon: "Flag",
    presentation: "timeline",
    universal: true,
    plural: "milestones",
    intro: "Dated checkpoints. The project deadline anchors the right edge; a countdown appears inside 30 days.",
    defaultSort: "date",
    entrySchema: [
      { key: "title", label: "Milestone", type: "text", isTitle: true, required: true },
      { key: "date", label: "Target date", type: "date", required: true, slot: "date" },
      { key: "done", label: "Reached", type: "select", options: ["no", "yes"] },
      { key: "note", label: "What this means", type: "longtext", prompt: "What has to be true for this to count as reached?" },
    ],
  },
  {
    key: "sources",
    name: "Sources & Research",
    icon: "BookMarked",
    presentation: "table",
    universal: true,
    plural: "sources",
    intro: "Anything you've read, watched or found that informs the project. What you took from it matters more than the citation.",
    entrySchema: [
      { key: "title", label: "Title", type: "text", isTitle: true, required: true },
      { key: "author", label: "Author", type: "text" },
      { key: "year", label: "Year", type: "number" },
      { key: "type", label: "Type", type: "select", options: ["book", "article", "paper", "video", "site", "conversation", "other"] },
      { key: "link", label: "Link", type: "link" },
      { key: "takeaway", label: "Key takeaway", type: "longtext", prompt: "In your own words, the one thing you want to remember from this." },
      { key: "relevance", label: "Why it matters here", type: "text" },
    ],
  },
  {
    key: "inspiration",
    name: "Inspiration",
    icon: "Images",
    presentation: "gallery",
    universal: true,
    plural: "references",
    intro: "Images, links, quotes — the mood and the reference points. Each one says why it's here.",
    entrySchema: [
      { key: "title", label: "Label", type: "text", isTitle: true },
      { key: "image", label: "Image", type: "image" },
      { key: "link", label: "Link", type: "link" },
      { key: "quote", label: "Quote", type: "longtext" },
      { key: "why", label: "Why this", type: "text", required: true, prompt: "What exactly are you taking from it? Not 'nice' — the specific thing." },
    ],
  },
  {
    key: "decisions_log",
    name: "Decisions Log",
    icon: "GitBranch",
    presentation: "list",
    universal: true,
    plural: "decisions",
    intro: "What you chose, what you rejected, and why. Future-you will want the reasoning, not just the outcome.",
    entrySchema: [
      { key: "decision", label: "What was decided", type: "text", isTitle: true, required: true },
      { key: "rejected", label: "What was rejected", type: "longtext" },
      { key: "why", label: "Why", type: "longtext", required: true },
      { key: "date", label: "When", type: "date" },
    ],
  },
  {
    key: "budget",
    name: "Budget",
    icon: "Wallet",
    presentation: "table",
    universal: true,
    plural: "lines",
    intro: "Item, estimate, actual, status. A running picture of what this costs.",
    entrySchema: [
      { key: "item", label: "Item", type: "text", isTitle: true, required: true },
      { key: "estimated", label: "Estimated", type: "money", slot: "estimated" },
      { key: "actual", label: "Actual", type: "money", slot: "actual" },
      { key: "status", label: "Status", type: "select", options: ["planned", "committed", "paid"] },
      { key: "note", label: "Note", type: "text" },
    ],
  },
  {
    key: "people",
    name: "People",
    icon: "Users",
    presentation: "table",
    universal: true,
    plural: "people",
    intro: "Everyone involved and what each of them is responsible for.",
    entrySchema: [
      { key: "name", label: "Name", type: "text", isTitle: true, required: true },
      { key: "role", label: "Role", type: "text" },
      { key: "contact", label: "Contact", type: "text" },
      { key: "responsible_for", label: "Responsible for", type: "longtext" },
    ],
  },
  {
    key: "files_assets",
    name: "Files & Assets",
    icon: "Paperclip",
    presentation: "gallery",
    universal: true,
    plural: "files",
    intro: "Uploads of any kind. Drafts, scans, exports, reference documents.",
    entrySchema: [
      { key: "title", label: "Name", type: "text", isTitle: true },
      { key: "file", label: "File", type: "file" },
      { key: "note", label: "Note", type: "text" },
    ],
  },
  {
    key: "glossary",
    name: "Glossary",
    icon: "Book",
    presentation: "table",
    universal: true,
    plural: "terms",
    intro:
      "Terms and names, defined once. Also feeds the transcription vocabulary — a name typed here is spelled right in every later recording.",
    entrySchema: [
      { key: "term", label: "Term", type: "text", isTitle: true, required: true },
      { key: "definition", label: "Definition", type: "longtext", required: true },
      { key: "aka", label: "Also known as", type: "text" },
    ],
  },
  {
    key: "activity_log",
    name: "Activity Log",
    icon: "Activity",
    presentation: "timeline",
    universal: true,
    plural: "events",
    intro: "Auto-populated. Entries created, questions resolved, modules added, sessions run. The honest answer to 'what did I actually do last month.'",
    entrySchema: [],
  },
];
