/**
 * Generates supabase/migrations/<ts>_seed_content.sql from the TypeScript
 * content registries. Run with `npm run gen:seed`. Commit the output.
 */
import { writeFileSync } from "fs";
import { join } from "path";
import { ALL_MODULES } from "../src/content/modules";
import { moduleId } from "../src/lib/schema/module-id";
import { BRAINSTORM_PROMPTS } from "../src/content/prompts";
import { CHAOS_TEMPLATES } from "../src/content/chaos";

const q = (s: string | null | undefined) =>
  s === null || s === undefined ? "null" : `'${s.replace(/'/g, "''")}'`;
const jsonb = (v: unknown) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const arr = (a: string[]) =>
  a.length ? `array[${a.map((x) => q(x)).join(",")}]::text[]` : `'{}'::text[]`;

const lines: string[] = [
  "-- AUTO-GENERATED by scripts/gen-seed.ts — do not edit by hand.",
  "-- Regenerate with `npm run gen:seed`.",
  "",
  "begin;",
  "",
  "-- module_definitions -------------------------------------------------------",
];

for (const m of ALL_MODULES) {
  const id = moduleId(m.key);
  lines.push(
    `insert into public.module_definitions
  (id, key, name, icon, presentation, intro, entry_schema, gap_rules,
   category_affinity, suggested_with, is_universal, author_id, is_public, version)
values
  ('${id}', ${q(m.key)}, ${q(m.name)}, ${q(m.icon)}, ${q(m.presentation)}, ${q(m.intro)},
   ${jsonb(m.entrySchema)}, ${jsonb(m.gapRules ?? [])},
   ${arr(m.categoryAffinity ?? [])}, ${arr(m.suggestedWith ?? [])},
   ${m.universal ? "true" : "false"}, null, true, 1)
on conflict (id) do update set
  name = excluded.name, icon = excluded.icon, presentation = excluded.presentation,
  intro = excluded.intro, entry_schema = excluded.entry_schema,
  gap_rules = excluded.gap_rules, category_affinity = excluded.category_affinity,
  suggested_with = excluded.suggested_with, is_universal = excluded.is_universal;`,
  );
}

lines.push("", "-- prompt_library ----------------------------------------------------------");
for (const p of BRAINSTORM_PROMPTS) {
  lines.push(
    `insert into public.prompt_library (key, topic, categories, subtypes, question, hint, alternates, followup_rules, order_index)
values (${q(p.key)}, ${q(p.topic)}, ${arr(p.categories)}, ${arr(p.subtypes ?? [])}, ${q(p.question)}, ${q(p.hint)}, ${jsonb(p.alternates ?? [])}, '[]'::jsonb, ${p.order})
on conflict (key) do update set
  topic = excluded.topic, categories = excluded.categories, subtypes = excluded.subtypes,
  question = excluded.question, hint = excluded.hint, alternates = excluded.alternates,
  order_index = excluded.order_index;`,
  );
}

lines.push("", "-- chaos_templates ---------------------------------------------------------");
lines.push("delete from public.chaos_templates;");
for (const c of CHAOS_TEMPLATES) {
  lines.push(
    `insert into public.chaos_templates (template, categories, slot_spec, weight)
values (${q(c.template)}, ${arr(c.categories)}, ${jsonb(c.slots)}, ${c.weight ?? 1});`,
  );
}

lines.push("", "commit;", "");

const stamp = "20260906090400";
const out = join(process.cwd(), "supabase", "migrations", `${stamp}_seed_content.sql`);
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out} — ${ALL_MODULES.length} modules, ${BRAINSTORM_PROMPTS.length} prompts, ${CHAOS_TEMPLATES.length} chaos templates.`);
